# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bgaifullin/Sources/git/moist/wsql

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bgaifullin/Sources/git/moist/wsql

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Development\" \"Readme\" \"SharedLibraries\" \"Test\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.0.0/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.0.0/bin/cpack --config ./CPackSourceConfig.cmake /Users/bgaifullin/Sources/git/moist/wsql/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bgaifullin/Sources/git/moist/wsql/CMakeFiles /Users/bgaifullin/Sources/git/moist/wsql/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bgaifullin/Sources/git/moist/wsql/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named INFO_BIN

# Build rule for target.
INFO_BIN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 INFO_BIN
.PHONY : INFO_BIN

# fast build rule for target.
INFO_BIN/fast:
	$(MAKE) -f CMakeFiles/INFO_BIN.dir/build.make CMakeFiles/INFO_BIN.dir/build
.PHONY : INFO_BIN/fast

#=============================================================================
# Target rules for targets named INFO_SRC

# Build rule for target.
INFO_SRC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 INFO_SRC
.PHONY : INFO_SRC

# fast build rule for target.
INFO_SRC/fast:
	$(MAKE) -f CMakeFiles/INFO_SRC.dir/build.make CMakeFiles/INFO_SRC.dir/build
.PHONY : INFO_SRC/fast

#=============================================================================
# Target rules for targets named ctags

# Build rule for target.
ctags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ctags
.PHONY : ctags

# fast build rule for target.
ctags/fast:
	$(MAKE) -f CMakeFiles/ctags.dir/build.make CMakeFiles/ctags.dir/build
.PHONY : ctags/fast

#=============================================================================
# Target rules for targets named gen_dtrace_header

# Build rule for target.
gen_dtrace_header: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_dtrace_header
.PHONY : gen_dtrace_header

# fast build rule for target.
gen_dtrace_header/fast:
	$(MAKE) -f CMakeFiles/gen_dtrace_header.dir/build.make CMakeFiles/gen_dtrace_header.dir/build
.PHONY : gen_dtrace_header/fast

#=============================================================================
# Target rules for targets named tags

# Build rule for target.
tags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tags
.PHONY : tags

# fast build rule for target.
tags/fast:
	$(MAKE) -f CMakeFiles/tags.dir/build.make CMakeFiles/tags.dir/build
.PHONY : tags/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f zlib/CMakeFiles/zlib.dir/build.make zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named yassl

# Build rule for target.
yassl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yassl
.PHONY : yassl

# fast build rule for target.
yassl/fast:
	$(MAKE) -f extra/yassl/CMakeFiles/yassl.dir/build.make extra/yassl/CMakeFiles/yassl.dir/build
.PHONY : yassl/fast

#=============================================================================
# Target rules for targets named taocrypt

# Build rule for target.
taocrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taocrypt
.PHONY : taocrypt

# fast build rule for target.
taocrypt/fast:
	$(MAKE) -f extra/yassl/taocrypt/CMakeFiles/taocrypt.dir/build.make extra/yassl/taocrypt/CMakeFiles/taocrypt.dir/build
.PHONY : taocrypt/fast

#=============================================================================
# Target rules for targets named dbug

# Build rule for target.
dbug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dbug
.PHONY : dbug

# fast build rule for target.
dbug/fast:
	$(MAKE) -f dbug/CMakeFiles/dbug.dir/build.make dbug/CMakeFiles/dbug.dir/build
.PHONY : dbug/fast

#=============================================================================
# Target rules for targets named conf_to_src

# Build rule for target.
conf_to_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conf_to_src
.PHONY : conf_to_src

# fast build rule for target.
conf_to_src/fast:
	$(MAKE) -f strings/CMakeFiles/conf_to_src.dir/build.make strings/CMakeFiles/conf_to_src.dir/build
.PHONY : conf_to_src/fast

#=============================================================================
# Target rules for targets named strings

# Build rule for target.
strings: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strings
.PHONY : strings

# fast build rule for target.
strings/fast:
	$(MAKE) -f strings/CMakeFiles/strings.dir/build.make strings/CMakeFiles/strings.dir/build
.PHONY : strings/fast

#=============================================================================
# Target rules for targets named vio

# Build rule for target.
vio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vio
.PHONY : vio

# fast build rule for target.
vio/fast:
	$(MAKE) -f vio/CMakeFiles/vio.dir/build.make vio/CMakeFiles/vio.dir/build
.PHONY : vio/fast

#=============================================================================
# Target rules for targets named regex

# Build rule for target.
regex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 regex
.PHONY : regex

# fast build rule for target.
regex/fast:
	$(MAKE) -f regex/CMakeFiles/regex.dir/build.make regex/CMakeFiles/regex.dir/build
.PHONY : regex/fast

#=============================================================================
# Target rules for targets named mysys

# Build rule for target.
mysys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysys
.PHONY : mysys

# fast build rule for target.
mysys/fast:
	$(MAKE) -f mysys/CMakeFiles/mysys.dir/build.make mysys/CMakeFiles/mysys.dir/build
.PHONY : mysys/fast

#=============================================================================
# Target rules for targets named queues

# Build rule for target.
queues: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 queues
.PHONY : queues

# fast build rule for target.
queues/fast:
	$(MAKE) -f mysys/CMakeFiles/queues.dir/build.make mysys/CMakeFiles/queues.dir/build
.PHONY : queues/fast

#=============================================================================
# Target rules for targets named thr_lock

# Build rule for target.
thr_lock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thr_lock
.PHONY : thr_lock

# fast build rule for target.
thr_lock/fast:
	$(MAKE) -f mysys/CMakeFiles/thr_lock.dir/build.make mysys/CMakeFiles/thr_lock.dir/build
.PHONY : thr_lock/fast

#=============================================================================
# Target rules for targets named mysys_ssl

# Build rule for target.
mysys_ssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysys_ssl
.PHONY : mysys_ssl

# fast build rule for target.
mysys_ssl/fast:
	$(MAKE) -f mysys_ssl/CMakeFiles/mysys_ssl.dir/build.make mysys_ssl/CMakeFiles/mysys_ssl.dir/build
.PHONY : mysys_ssl/fast

#=============================================================================
# Target rules for targets named clientlib

# Build rule for target.
clientlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clientlib
.PHONY : clientlib

# fast build rule for target.
clientlib/fast:
	$(MAKE) -f libmysql/CMakeFiles/clientlib.dir/build.make libmysql/CMakeFiles/clientlib.dir/build
.PHONY : clientlib/fast

#=============================================================================
# Target rules for targets named libmysql

# Build rule for target.
libmysql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmysql
.PHONY : libmysql

# fast build rule for target.
libmysql/fast:
	$(MAKE) -f libmysql/CMakeFiles/libmysql.dir/build.make libmysql/CMakeFiles/libmysql.dir/build
.PHONY : libmysql/fast

#=============================================================================
# Target rules for targets named mysqlclient

# Build rule for target.
mysqlclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqlclient
.PHONY : mysqlclient

# fast build rule for target.
mysqlclient/fast:
	$(MAKE) -f libmysql/CMakeFiles/mysqlclient.dir/build.make libmysql/CMakeFiles/mysqlclient.dir/build
.PHONY : mysqlclient/fast

#=============================================================================
# Target rules for targets named symlink_libmysqlclient_r.18.dylib

# Build rule for target.
symlink_libmysqlclient_r.18.dylib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 symlink_libmysqlclient_r.18.dylib
.PHONY : symlink_libmysqlclient_r.18.dylib

# fast build rule for target.
symlink_libmysqlclient_r.18.dylib/fast:
	$(MAKE) -f libmysql/CMakeFiles/symlink_libmysqlclient_r.18.dylib.dir/build.make libmysql/CMakeFiles/symlink_libmysqlclient_r.18.dylib.dir/build
.PHONY : symlink_libmysqlclient_r.18.dylib/fast

#=============================================================================
# Target rules for targets named symlink_libmysqlclient_r.a

# Build rule for target.
symlink_libmysqlclient_r.a: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 symlink_libmysqlclient_r.a
.PHONY : symlink_libmysqlclient_r.a

# fast build rule for target.
symlink_libmysqlclient_r.a/fast:
	$(MAKE) -f libmysql/CMakeFiles/symlink_libmysqlclient_r.a.dir/build.make libmysql/CMakeFiles/symlink_libmysqlclient_r.a.dir/build
.PHONY : symlink_libmysqlclient_r.a/fast

#=============================================================================
# Target rules for targets named symlink_libmysqlclient_r.dylib

# Build rule for target.
symlink_libmysqlclient_r.dylib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 symlink_libmysqlclient_r.dylib
.PHONY : symlink_libmysqlclient_r.dylib

# fast build rule for target.
symlink_libmysqlclient_r.dylib/fast:
	$(MAKE) -f libmysql/CMakeFiles/symlink_libmysqlclient_r.dylib.dir/build.make libmysql/CMakeFiles/symlink_libmysqlclient_r.dylib.dir/build
.PHONY : symlink_libmysqlclient_r.dylib/fast

#=============================================================================
# Target rules for targets named GenError

# Build rule for target.
GenError: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenError
.PHONY : GenError

# fast build rule for target.
GenError/fast:
	$(MAKE) -f extra/CMakeFiles/GenError.dir/build.make extra/CMakeFiles/GenError.dir/build
.PHONY : GenError/fast

#=============================================================================
# Target rules for targets named comp_err

# Build rule for target.
comp_err: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comp_err
.PHONY : comp_err

# fast build rule for target.
comp_err/fast:
	$(MAKE) -f extra/CMakeFiles/comp_err.dir/build.make extra/CMakeFiles/comp_err.dir/build
.PHONY : comp_err/fast

#=============================================================================
# Target rules for targets named my_print_defaults

# Build rule for target.
my_print_defaults: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_print_defaults
.PHONY : my_print_defaults

# fast build rule for target.
my_print_defaults/fast:
	$(MAKE) -f extra/CMakeFiles/my_print_defaults.dir/build.make extra/CMakeFiles/my_print_defaults.dir/build
.PHONY : my_print_defaults/fast

#=============================================================================
# Target rules for targets named perror

# Build rule for target.
perror: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perror
.PHONY : perror

# fast build rule for target.
perror/fast:
	$(MAKE) -f extra/CMakeFiles/perror.dir/build.make extra/CMakeFiles/perror.dir/build
.PHONY : perror/fast

#=============================================================================
# Target rules for targets named resolveip

# Build rule for target.
resolveip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resolveip
.PHONY : resolveip

# fast build rule for target.
resolveip/fast:
	$(MAKE) -f extra/CMakeFiles/resolveip.dir/build.make extra/CMakeFiles/resolveip.dir/build
.PHONY : resolveip/fast

#=============================================================================
# Target rules for targets named mysql_client_test

# Build rule for target.
mysql_client_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysql_client_test
.PHONY : mysql_client_test

# fast build rule for target.
mysql_client_test/fast:
	$(MAKE) -f tests/CMakeFiles/mysql_client_test.dir/build.make tests/CMakeFiles/mysql_client_test.dir/build
.PHONY : mysql_client_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... INFO_BIN"
	@echo "... INFO_SRC"
	@echo "... ctags"
	@echo "... edit_cache"
	@echo "... gen_dtrace_header"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... tags"
	@echo "... zlib"
	@echo "... yassl"
	@echo "... taocrypt"
	@echo "... dbug"
	@echo "... conf_to_src"
	@echo "... strings"
	@echo "... vio"
	@echo "... regex"
	@echo "... mysys"
	@echo "... queues"
	@echo "... thr_lock"
	@echo "... mysys_ssl"
	@echo "... clientlib"
	@echo "... libmysql"
	@echo "... mysqlclient"
	@echo "... symlink_libmysqlclient_r.18.dylib"
	@echo "... symlink_libmysqlclient_r.a"
	@echo "... symlink_libmysqlclient_r.dylib"
	@echo "... GenError"
	@echo "... comp_err"
	@echo "... my_print_defaults"
	@echo "... perror"
	@echo "... resolveip"
	@echo "... mysql_client_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

